"""Markdown report from doctor output."""

from __future__ import annotations

from pathlib import Path

from mission_preflight.doctor import diagnose_receipt
from mission_preflight.store import read_json


def write_report(receipt_path: Path, output: Path | None = None) -> Path:
    receipt_path = receipt_path.expanduser().resolve()
    if not (receipt_path / "doctor.json").exists():
        diagnose_receipt(receipt_path)

    doctor = read_json(receipt_path / "doctor.json")
    summary = read_json(receipt_path / "summary.json") if (receipt_path / "summary.json").exists() else {}
    plan = read_json(receipt_path / "plan.json") if (receipt_path / "plan.json").exists() else {}

    out_path = output or (receipt_path / "report.md")
    lines = [
        f"# Mission preflight report — {doctor.get('mission_id', summary.get('mission_id', 'unknown'))}",
        "",
        f"**Run ID:** `{doctor.get('run_id')}`  ",
        f"**Overall:** {doctor.get('overall_status')}  ",
        f"**Launch recommendation:** `{doctor.get('launch_recommendation')}`  ",
        "",
        "## Mission",
        "",
        f"- Operation: {summary.get('operation', plan.get('operation', '—'))}",
        f"- Waiver profile: {summary.get('waiver_profile', plan.get('waiver_profile', '—'))}",
        f"- Drones: {summary.get('drone_count', plan.get('drone_count', '—'))}",
        "",
    ]

    if plan.get("risks"):
        lines.extend(["## Plan risks", ""])
        for risk in plan["risks"]:
            lines.append(f"- {risk}")
        lines.append("")

    lines.extend(["## Doctor checks", ""])
    for check in doctor.get("checks", []):
        icon = {"pass": "✓", "warn": "!", "fail": "✗"}.get(check["status"], "?")
        lines.append(f"- [{icon}] **{check['signal']}** — {check['message']}")

    lines.extend(
        [
            "",
            "---",
            "",
            "*Generated by [Mission Preflight Workbench](https://github.com/Abhishek21g/skydio-mission-preflight).*",
            "",
        ]
    )

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path
